version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.0-flash}
      - GEMINI_RATE_LIMIT=${GEMINI_RATE_LIMIT:-60}
      - WEATHER_RATE_LIMIT=${WEATHER_RATE_LIMIT:-60}
    volumes:
      - ./static:/app/static
    restart: unless-stopped
